/// Generated by clips-unnamed-library

#include "clips/clips.h"

static void UNNAMED_close_piped_command(
	Environment *env, UDFContext *udfc, UDFValue *out)
{
	UDFValue name;

	UDFFirstArgument(udfc, SYMBOL_BIT, &name);

	struct fileRouter *p;
	struct fileRouter *prev = NULL;
	for (p = FileRouterData(env)->ListOfFileRouters;
	     p != NULL;
	     p = p->next, prev = p) {
		if (strcmp(p->logicalName, name.lexemeValue->contents) != 0)
			continue;

		pclose(p->stream);
		rm(env, (void *)p->logicalName, strlen(p->logicalName) + 1);
		if (prev == NULL)
			FileRouterData(env)->ListOfFileRouters = p->next;
		else
			prev->next = p->next;
		rm(env, p, sizeof(struct fileRouter));

		break;
	}
}

static void UNNAMED_open_piped_command(
	Environment *env, UDFContext *udfc, UDFValue *out)
{
	UDFValue command, name, mode;

	UDFNthArgument(udfc, 1, STRING_BIT, &command);
	UDFNthArgument(udfc, 2, SYMBOL_BIT, &name);
	UDFNthArgument(udfc, 3, STRING_BIT, &mode);

	struct fileRouter *router = get_struct(env, fileRouter);
	router->logicalName = gm2(env, strlen(name.lexemeValue->contents) + 1);
	strcpy((char *)router->logicalName, name.lexemeValue->contents);
	router->stream = popen(command.lexemeValue->contents,
			       mode.lexemeValue->contents);
	router->next = FileRouterData(env)->ListOfFileRouters;
	FileRouterData(env)->ListOfFileRouters = router;
}

void UserFunctions(Environment *env)
{
	AddUDF(env,
	       "UNNAMED-close-piped-command",
	       "v", 1, 1, "y",
	       UNNAMED_close_piped_command, "UNNAMED_close_piped_command",
	       NULL);

	AddUDF(env,
	       "UNNAMED-open-piped-command",
	       "v", 3, 3, "sys",
	       UNNAMED_open_piped_command, "UNNAMED_open_piped_command",
	       NULL);

}
